class Example8
{
	public static void main(String[] args)
	{
		try
		{
			System.out.println("These is the try block...");
			System.out.println(10/2);	
		}
		// It is manditory to use the catch block if try block is successfull or not an exception in that.
		
	}
}

/*
	Example8.java:5: error: 'try' without 'catch', 'finally' or resource declarations
                try
                ^
*/

// It is manditory to use the catch block if try block is successfull or not an exception in that.